### ISSUE TITLE
Module dont show up in Modules

### ISSUE THREAD

**Issue by christophermp** [petersmithca/humhub-adsense#9]
Hi there!

For me it seems that there may be an error when i upload it to >yourdomain.com>protected>modules
Because it wont show up in modules.
Any solution on this on what may be wrong here?

**Comment by petersmithca** [comment]
I'vr not tried it in the beta, but I am not aware of there being any changes that would cause this. Things to try
1. Can you get any other 3rd party module to work?
2.  Did perhaps you upload a folder containing the folder, rather than the root folder?
3. Does your wwww-data have ownership/permissions to read the files?

**Comment by christophermp** [comment]
Hi there!
1. I am not able to get any modules to work (not limited to one installation)
2. Files are in root /public_html/SITENAME/protected/modules/adsense (no extra folder, just main files)
3. Yes, just for test i have tried to 777 my way to the top

Both of the sites are running the beta version.

**Comment by christophermp** [comment]
A little update her, it worke perfectly. I had to `ipconfig /flushdns` to make it work  :)

**Comment by petersmithca** [comment]
Ok thank you, closing issue
